config/routes.rb
Quick::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  root to: 'pages#home'
  
  match '/about', to: 'pages#about'

  match '/contact', to: 'pages#contact'

  match '/privacy', to: 'pages#privacy'

  match '/terms', to: 'pages#terms'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  					format: { with: valid_email_regex }, 
  					uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def terms
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user,   only: [:edit, :update]

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Quick Score!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end


  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo
    image_tag("logo.png", alt: "Quick Score", class: "round")
  end
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Quick-Score.com"
    if page_title.empty?
      base_title
    else
      "#{page_title} @ #{base_title}"
    end
  end

  # Returns a div wrapper around the error fields so we can ammend the styling of these ugly fields.
  def error_field_div_wrapper(error_field,cssField,is_error)
    if !is_error.eql?(0)
      returnValue = content_tag(:div, error_field, class: "#{cssField}")
      returnValue 
    else
      error_field
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
    current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def current_user?(user)
    user == current_user
  end
  
  def sign_out
    cookies.delete(:remember_token)
  end

  private

    def clear_return_to
      session.delete(:return_to)
    end

    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <!-- <li><%= link_to 'Home', root_path  %></li>
      <li><%= link_to 'About', about_path %></li> -->
      <li><%= link_to 'Terms', terms_path %></li>
      <li><%= link_to 'Privacy', privacy_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <div id="header-ad" class="round"></div>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <!-- <li><%= link_to "Privacy", privacy_path %></li> -->
      <% if signed_in? %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
        <li><%= link_to "Sign Up", signup_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', media: 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  media: 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag    "application", media: "all" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <section class="round">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "flash #{key}") %>
      <% end %>
      <%= yield %>
    </section>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<p>Find me in app/views/pages/contact.html.erb testing</p>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Home</h1>
<h2><!-- Who Won What, When, Where and How? --></h2>
<div class="">
<!-- Make no mistake, this App. is for Competitive People.<br />
Create a Scoreboard so you and your friends can keep track of the real Score. -->
</div>
<div id="loginButtons">

<% if !signed_in? %>
<%= link_to "Sign up now!", signup_path, class: "signup_button round" %>
<%= link_to "Sign In", signin_path, class: "signin_button round" %>
<% end %>
<%= link_to "Facebook Login", signup_path, class: "facebook_button round" %>
</div>

app/views/pages/privacy.html.erb
<% provide(:title, 'Privacy') %>
<h1>Privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<% provide(:title, 'Terms of Service') %>
<h1>Terms of Service</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        were encountered:</h2>
    There were problems with the following <%= pluralize(@user.errors.count, "field") %>:
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide :title, "Edit user" %> 
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for(@user) %>
  <%= link_to "change", "http://gravatar.com/emails", target: "_blank" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <%
    @errorMessageLength = (render 'shared/error_messages').length
  %>
  <div class="field">
    <%= (error_field_div_wrapper((f.label :name),"errorLabelFix",@errorMessageLength)) %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= (error_field_div_wrapper((f.label :email),"errorLabelFix",@errorMessageLength)) %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= (error_field_div_wrapper((f.label :password),"errorLabelFix",@errorMessageLength)) %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<span id="gravatar">
  <%= gravatar_for @user %>
</span>
<span id="userLinks" class="round">
  Scoreboards
  <br />
  Quotes
  <br />
  <%= link_to user_path(@user), @user %>
  <br />
  Quotessdaf
  <br />
  Quotes
  <br />
  Quotes
  <br />
  Quotes
  <br />
  Quotes
</span>
<h1><%= @user.name %></h1>